import java.io.File

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.devtools.ksp")
    id("com.google.dagger.hilt.android")
}

android {
    namespace = "com.panyou.missnet"
    compileSdk = 35

    // ── Signing config ─────────────────────────────────────────────────────────
    // keystore is generated by the CI workflow at app/debug.keystore (relative to
    // the miss_net_native/ working directory, so absolute path below).
    // Build type "debug" references this config automatically.
    val keystoreDir = project.rootDir.resolve("miss_net_native").resolve("app")
    val keystoreFile = keystoreDir.resolve("debug.keystore")

    if (keystoreFile.exists()) {
        signingConfigs.create("ci") {
            storeFile = keystoreFile
            storePassword = "MissNet2026"
            keyAlias = "missnet-debug"
            keyPassword = "MissNet2026"
        }
    }

    defaultConfig {
        applicationId = "com.panyou.missnet"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        vectorDrawables {
            useSupportLibrary = true
        }

        ndk {
            abiFilters += listOf("arm64-v8a")
        }
    }

    buildTypes {
        debug {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (keystoreFile.exists()) {
                signingConfig = signingConfigs.getByName("ci")
            }
        }

        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
}
